#!/bin/sh

echo "Running code analysis with ktlint..."

./gradlew checkstyle ktlint --daemon

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis ran successfully."
    exit 0
else
    echo "Static analysis failed. Formatting with ktlint..."
    ./gradlew ktlintFormat --stacktrace
    exit 1
fi
