version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:00"
    groups:
      ktx:
        patterns:
          - "fragment-ktx"
          - "core-ktx"
      kotlin:
        patterns:
          - "android" # released together with the ones below
          - "kotlin"
          - "kotlin_version"
          - "org.jetbrains.kotlin*"
    reviewers:
      - sethonyango
    ignore:
      # Ignore patch updates for some packages
      - dependency-name: "mockito-*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "appcompat"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "02:00"
    reviewers:
      - sethonyango
      - mburumaxwell
