version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
    - SecyWecy
    - mburumaxwell
    ignore:
    # Ignore patch updates for some packages
    - dependency-name: "mockito-*"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "appcompat"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "fragment-ktx"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "core-ktx"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "com.android.tools.build*"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "kotlin_version"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "kotlin"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "android"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "org.jetbrains.kotlin*"
      update-types: ["version-update:semver-patch"]
