version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "02:00"
    open-pull-requests-limit: 20
    groups:
      ktx:
        patterns:
          - "fragment-ktx"
          - "core-ktx"
      kotlin:
        patterns:
          - "kotlin"
          - "kotlin_version"
          - "org.jetbrains.kotlin*"
      android:
        patterns:
          - "android"
          - "com.android.tools.build*"
    reviewers:
      - mburumaxwell
    ignore:
      # Ignore patch updates for some packages
      - dependency-name: "mockito-*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "appcompat"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      time: "02:00"
    open-pull-requests-limit: 10
    reviewers:
      - mburumaxwell
