package io.falu.android.models.evaluations

import android.os.Parcelable
import com.google.gson.annotations.JsonAdapter
import kotlinx.parcelize.Parcelize
import software.tingle.api.adapters.ISO8601DateAdapter
import java.util.*

/**
 * Represents details about the statement used for an evaluation.
 */
@Parcelize
data class EvaluationStatement(
    /**
     * Represents the kind of provider used for a statement in an evaluation.
     */
    var provider: StatementProvider?,

    /**
     * Email found in the statement.
     */
    var email: String?,

    /**
     * Name found in the statement
     */
    var name: String?,

    /**
     * Phone number found in the statement.
     */
    var phone: String?,

    /**
     * Time at which the statement was generated by the provider.
     */
    @JsonAdapter(ISO8601DateAdapter::class)
    var generated: Date?,

    /**
     * The period of the statement
     */
    var period: Period?

) : Parcelable

@Parcelize
data class Period(
    var start: Date?,
    var end: Date?
) : Parcelable