package io.falu.android.models.payments

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import kotlinx.parcelize.Parcelize

/**
 * [The Mpesa Payment object](https://falu.io)
 */
@Parcelize
data class Mpesa(
    /**
     * Type of payment
     */
    var type: PaymentType?,

    /**
     * Reference the payment was made in.
     */
    var reference: String?,

    /**
     * Phone number that made the payment, in E.164 format.
     */
    var phone: String?,

    /**
     * Name of the entity making or that made the payment.
     */
    var payer: String?,

    /**
     * The target business short code
     */
    @SerializedName("business_short_code")
    var businessShortCode: String?,

    /**
     * Unique transaction identifier generated by Mpesa.
     * Only populated for completed transactions.
     */
    var receipt: String?
) : Parcelable